import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About Page",
  description: "Generated by Fernando Herrera",
  keywords: ["about", "page", "nextjs"],
};

export default function AboutPage() {
  return (
      <span className="text-5xl">About Page</span>
  );
}
